<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-11 at 09:57:34.
 */
class SocioTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Socio
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		require "include/initialize.inc";
        $this->object = new Socio;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

	public function testCargarSocioDesdeLaDB(){
		$socio = new Socio(2);
		$this->assertEmpty($socio);
	}
}
